apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ifoundryanalysis
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.label.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.label.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.label.name }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}:{{ .Values.container.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            {{- if .Values.resources.requests.cpu }}
            cpu: {{ .Values.resources.requests.cpu }}
            {{- end }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            {{- if .Values.resources.limits.cpu }}
            cpu: {{ .Values.resources.limits.cpu }}
            {{- end }}