apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-one
  namespace: lobpoc
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: testacrpoc08112023.azurecr.io/demo_image:DOCKER_TAG
        ports:
        - containerPort: 8100
