apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: lobpoc
spec:  
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8100
  type: LoadBalancer