# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: DOTNET

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      image: rancher/dind:latest

    steps:
    - uses: actions/checkout@v3
    - name: install azcli
      run: |
        apt-get update
        apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/keyrings/microsoft.gpg > /dev/null 
        chmod go+r /etc/apt/keyrings/microsoft.gpg
        apt-get update
        apt-get install azure-cli
    - name: az login
      run: |
        az login --service-principal -u ${{secrets.user}} -p ${{secrets.password}} -t "5461eb53-e0fd-4320-92ff-c6efe1fe91e9"    
    
